import 'package:flutter/material.dart';
import 'package:munch_or_dump/core/theme/palette.dart';
import 'package:munch_or_dump/core/widgets/editorial.dart';

/// One titled section of a legal document.
class _Section {
  const _Section(this.title, this.paragraphs);
  final String title;
  final List<String> paragraphs;
}

/// Renders a legal/privacy document: eyebrow, title, "last updated", sections,
/// and a footer note — in the editorial style.
class _LegalDoc extends StatelessWidget {
  const _LegalDoc({
    required this.appBarTitle,
    required this.eyebrow,
    required this.title,
    required this.lastUpdated,
    required this.sections,
    this.intro,
    this.footer,
  });

  final String appBarTitle;
  final String eyebrow;
  final String title;
  final String lastUpdated;
  final List<_Section> sections;
  final String? intro;
  final String? footer;

  @override
  Widget build(BuildContext context) {
    final palette = context.palette;
    return Scaffold(
      appBar: AppBar(title: Text(appBarTitle)),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(24, 8, 24, 40),
        children: <Widget>[
          Eyebrow(eyebrow, spacing: 4),
          const SizedBox(height: 10),
          Text(
            title,
            style: TextStyle(
              fontSize: 30,
              height: 1.1,
              fontWeight: FontWeight.w800,
              letterSpacing: -0.6,
              color: palette.inkPrimary,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            lastUpdated,
            style: TextStyle(fontSize: 13, color: palette.inkFaint),
          ),
          if (intro != null) ...<Widget>[
            const SizedBox(height: 16),
            Text(
              intro!,
              style: TextStyle(
                fontSize: 16,
                height: 1.5,
                color: palette.inkSecondary,
              ),
            ),
          ],
          const SizedBox(height: 28),
          for (final section in sections) ...<Widget>[
            Eyebrow(section.title, spacing: 3),
            const SizedBox(height: 10),
            for (final paragraph in section.paragraphs)
              Padding(
                padding: const EdgeInsets.only(bottom: 10),
                child: Text(
                  paragraph,
                  style: TextStyle(
                    fontSize: 14.5,
                    height: 1.55,
                    color: palette.inkSecondary,
                  ),
                ),
              ),
            const SizedBox(height: 18),
          ],
          if (footer != null) ...<Widget>[
            Divider(color: palette.hairline, height: 32),
            Text(
              footer!,
              style: TextStyle(fontSize: 12, color: palette.inkFaint),
            ),
          ],
        ],
      ),
    );
  }
}

/// Disclaimers & Terms — the satire/defamation shield + medical/allergen
/// disclaimers, ported from the web Legal page.
class LegalScreen extends StatelessWidget {
  const LegalScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const _LegalDoc(
      appBarTitle: 'Disclaimers & Terms',
      eyebrow: 'Legal',
      title: 'Disclaimers & Terms',
      lastUpdated: 'Last updated: June 2026',
      sections: <_Section>[
        _Section('Satire & Entertainment', <String>[
          'Munch or Dump is satire and entertainment. Every verdict in this '
              'app is generated by an AI model and reflects a subjective, '
              'automated opinion, not a factual assessment of any product, '
              'brand, or company.',
          'Verdicts are not claims of fact. Labels like DUMP, ENGINEERED, or '
              'BULLSHIT are opinions and editorial shorthand, not statements '
              'that a product is unsafe, defective, mislabeled, or that any '
              'company has acted dishonestly.',
          'We are not affiliated with, endorsed by, or sponsored by any brand '
              'featured. Trademarks and product names belong to their '
              'respective owners and are used for identification and commentary '
              'only.',
        ]),
        _Section('AI-Generated Verdicts', <String>[
          'All product verdicts, scores, ingredient analyses, and '
              'recommendations are generated using artificial intelligence '
              'models, including large language models. They do not represent '
              'the opinions or assessments of licensed nutritionists, '
              'dietitians, physicians, or any other healthcare professionals.',
          'AI-generated content may contain errors, omissions, or outdated '
              'information. Ingredient formulations change over time and our '
              'database may not reflect the most current product composition. '
              'Always verify ingredient information directly from the product '
              'packaging before making purchasing or consumption decisions.',
        ]),
        _Section('Not Medical or Dietary Advice', <String>[
          'Nothing in this app constitutes medical advice, dietary advice, or '
              'a substitute for professional nutritional guidance. Munch or '
              'Dump is an informational tool only. If you have a medical '
              'condition, food allergy, dietary restriction, or specific health '
              'concern, consult a qualified healthcare provider before making '
              'decisions based on content from this app.',
          'Verdicts such as “MUNCH,” “DUMP,” “TREAT,” and others are simplified '
              'editorial classifications intended for general informational '
              'purposes. They do not account for individual health '
              'circumstances, specific medical needs, portion sizes, frequency '
              'of consumption, or the full context of a person’s diet.',
        ]),
        _Section('Ingredient Data Sources', <String>[
          'Product ingredient data is sourced from a combination of: '
              'user-submitted label photographs, barcode lookups via '
              'third-party databases (including Open Food Facts), and web '
              'search retrieval. We make reasonable efforts to ensure accuracy '
              'but cannot guarantee that ingredient information is complete, '
              'current, or free from error. Products identified as sourced from '
              'web searches are flagged for administrative review.',
        ]),
        _Section('No Warranties', <String>[
          'Munch or Dump is provided “as is” without warranties of any kind, '
              'express or implied. We make no warranty that the app will be '
              'uninterrupted, error-free, or that any verdict, analysis, or '
              'score is accurate, complete, or suitable for any particular '
              'purpose.',
          'To the fullest extent permitted by applicable law, Munch or Dump and '
              'its operators disclaim all liability for any direct, indirect, '
              'incidental, consequential, or punitive damages arising from use '
              'of or reliance on content generated by this app.',
        ]),
        _Section('Allergen Warning', <String>[
          'Munch or Dump is not a reliable source for allergen information. Do '
              'not rely on this app to determine whether a product is safe for '
              'consumption if you have food allergies or intolerances. Always '
              'read the physical product label and consult a healthcare '
              'professional for allergy-related dietary decisions.',
        ]),
        _Section('Intellectual Property', <String>[
          'Product names, brand names, and trademarks referenced in this app '
              'are the property of their respective owners. Their appearance '
              'does not imply endorsement of or by Munch or Dump. Analysis and '
              'editorial content generated by Munch or Dump is original work '
              'and may not be reproduced without attribution.',
        ]),
        _Section('Reporting & Corrections', <String>[
          'For questions regarding these terms or to report inaccurate '
              'information, contact us at hello@munchordump.com and we will '
              'review or remove it promptly.',
        ]),
      ],
      footer:
          'By using Munch or Dump you acknowledge that you have read and '
          'understood these disclaimers and agree that use of the app is at '
          'your own discretion and risk.',
    );
  }
}

/// Privacy policy — ported from the web Privacy page, with added disclosures
/// the app needs (health-condition data and AI sub-processors).
class PrivacyScreen extends StatelessWidget {
  const PrivacyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const _LegalDoc(
      appBarTitle: 'Privacy',
      eyebrow: 'Privacy',
      title: 'Your data stays yours.',
      lastUpdated: 'Last updated: June 2026',
      intro:
          'We built Munch or Dump to analyze products, not people. Here’s '
          'exactly what happens with your data.',
      sections: <_Section>[
        _Section('Images used only for analysis', <String>[
          'When you upload a label image, it is processed solely to extract '
              'ingredient and nutrition data for your analysis. We do not use '
              'your images for training, marketing, or any purpose beyond '
              'generating your verdict.',
        ]),
        _Section('Snapshots stored anonymously', <String>[
          'Product snapshots are stored to power the verdict library and '
              'improve analysis quality. These snapshots contain only product '
              'data — never personal information. They cannot be traced back '
              'to any individual user.',
        ]),
        _Section('Health information you provide', <String>[
          'If you set up a profile, the diet, goals, and health conditions you '
              'choose (for example diabetes or pregnancy) are used only to '
              'personalize your verdicts. This information is stored with your '
              'account, is never sold, and is used for no purpose other than '
              'tailoring your “For You” notes. You can edit or remove it any '
              'time from your account, and you don’t have to provide any of it '
              'to use the app.',
        ]),
        _Section('Who processes your data', <String>[
          'To generate verdicts we share product and ingredient text with AI '
              'and search providers — OpenAI, Anthropic, and Tavily — and use '
              'Amazon Web Services for hosting and image storage and Google for '
              'optional sign-in. These providers process data on our behalf to '
              'deliver the service and not for their own purposes.',
        ]),
        _Section('No personal tracking', <String>[
          'We don’t track your browsing behavior, sell your data, or build '
              'advertising profiles. Munch or Dump exists to analyze products, '
              'not people.',
        ]),
      ],
      footer:
          'If you have questions about your data, or want your account and data '
          'deleted, contact us at hello@munchordump.com and we’ll respond with '
          'the same directness we apply to product labels.',
    );
  }
}
